# User Settings | Edit there as per required

title: deep dumpster
url: "https://james-chuang.github.io/"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    <a href=https://james-chuang.github.io/>the deep dumpster</a>
    
#<span class="faded">the deep dumpster</span>

email: deep.dumpster@gmail.com
author: James Chuang
# This description will show up in google search results
# (for index page) etc.
description: >
    A log of my attempts to learn statistics, data science, and machine learning.

# This will what will show against &copy; in the footer
copyright: <a href=https://james-chuang.github.io/>the deep dumpster</a>
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: true         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    A log of my notes on statistics/data science/machine learning.
permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Currently lost on the road of life.

about_footer: true

twitter_username: 
github_username: james-chuang
facebook_id:

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 10
paginate_path: "/page/:num"
tracking_id: # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
